name: Build and Push Docker Images

# trigger on pull requests to main and workflow call from release.yml

on:
  workflow_call:
  workflow_dispatch:

env:
  GHCR: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64

jobs:
  build-docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Set up docker buildx for push
        uses: docker/setup-buildx-action@v3


      - name: Set tag types
        run: |
          if [ ${{ github.event_name }} == "push" ]; then
            echo 'METATAGS=type=semver,pattern={{version}} type=raw,value=latest,enable={{is_default_branch}}" >> $GITHUB_ENV
          else
            echo "METATAGS=type=sha" >> $GITHUB_ENV
          fi

      - name: Metadata for xion container
        id: meta-xion
        uses: docker/metadata-action@v5
        with:
          images: |
            burntnetwork/xion
            ${{ env.GHCR }}/xion
            385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/xiond
          tags: ${{ env.METATAGS }}

      - name: Prepare xion build environment
        run: |
          echo "VERSION=$(shell echo $(shell git describe --tags) | sed 's/^v//')" >> $GITHUB_ENV
          echo "COMMIT=$(shell git log -1 --format='%H')" >> $GITHUB_ENV
          echo "TAG_VERSION=$(shell git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push xion image
        uses: docker/build-push-action@v5
        env:
          COMMIT: ${{ env.COMMIT }}
          VERSION: ${{ env.VERSION }}
          TAG_VERSION: ${{ env.TAG_VERSION }}
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: release
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta-xion.outputs.tags }}
          labels: ${{ steps.meta-xion.outputs.labels }}

      - name: Prepare heighliner build
        run: |
          mkdir -p ./heighliner
          curl -sSL https://raw.githubusercontent.com/strangelove-ventures/heighliner/main/dockerfile/imported/Dockerfile -o ./heighliner/Dockerfile
          echo ""

      - name: Metadata for heighliner
        id: meta-heighliner
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR }}/heighliner
          tags: ${{ env.METATAGS }}

      - name: Prepare heighliner build
        run: |
          curl -vL https://raw.githubusercontent.com/strangelove-ventures/heighliner/main/dockerfile/imported/Dockerfile -o ${{ runner.temp }}/Dockerfile.heighliner
          echo "IMAGE_VERSION=$(echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '.labels["org.opencontainers.image.version"]')" >> $GITHUB_ENV

      - name: Build and push heighliner image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ runner.temp }}/Dockerfile.heighliner
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta-heighliner.outputs.tags }}
          labels: ${{ steps.meta-heighliner.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.GHCR }}/xion
            VERSION=${{ env.IMAGE_VERSION }}
            BINARIES=/usr/bin/xiond

      - name: Run Docker Scout amd64
        uses: docker/scout-action@v1
        with:
          command: cves
          only-fixed: true
          platforms: ${{ env.PLATFORMS }}
          image: ${{ env.GHCR }}/xion:${{ env.IMAGE_VERSION }}
