name: Build and Push Docker Images

# build for pull requests to main, releases are handled in release.yml

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  GHCR: ghcr.io/${{ github.repository }}
  platforms: linux/amd64

jobs:
  docker-scout:
    name: Build Image
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Set up docker buildx for push
        uses: docker/setup-buildx-action@v3

      - name: Metadata for xion container
        id: meta-xion
        uses: docker/metadata-action@v5
        with:
          images: |
            burntnetwork/xion
            ${{ env.GHCR }}/xion
            385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/xiond
          tags: |
            type=sha

      - name: Build and push xion image
        uses: docker/build-push-action@v5
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: release
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta-xion.outputs.tags }}
          labels: ${{ steps.meta-xion.outputs.labels }}

      - name: Prepare heighliner build
        run: |
          mkdir -p ./heighliner
          curl -sSL https://raw.githubusercontent.com/strangelove-ventures/heighliner/main/dockerfile/imported/Dockerfile -o ./heighliner/Dockerfile
          echo ""

      - name: Metadata for heighliner
        id: meta-heighliner
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR }}/heighliner
          tags: |
            type=sha

      - name: Prepare heighliner build
        run: |
          mkdir -p ./heighliner
          curl -sSL https://raw.githubusercontent.com/strangelove-ventures/heighliner/main/dockerfile/imported/Dockerfile -o ./heighliner/Dockerfile
          echo "SHA_VERSION=$(echo "$DOCKER_METADATA_OUTPUT_JSON" | jq -r '.labels["org.opencontainers.image.version"]')" | >> $GITHUB_ENV

      - name: Build and push heighliner image
        uses: docker/build-push-action@v5
        with:
          push: true
          dockerfile: heighliner/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta-heighliner.outputs.tags }}
          labels: ${{ steps.meta-heighliner.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.GHCR }}/xion
            VERSION=${{ env.SHA_VERSION }}
            BINARIES=/usr/bin/xiond

      - name: Run Docker Scout amd64
        uses: docker/scout-action@v1
        with:
          command: cves
          only-fixed: true
          platform: linux/amd64
          image: ${{ env.GHCR }}/xion:${{ env.SHA_VERSION }}
