name: Heighliner Build

on:
  workflow_call:

env:
  GHCR: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64

jobs:
  build-heighliner:
    name: Heighliner Build
    runs-on: ubuntu-latest
    environment: CI
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Set tag types
        run: |
          if [ ${{ github.event_name }} == "push" ]; then
            echo "METATAGS=type=semver,pattern={{version}} type=raw,value=latest,enable={{is_default_branch}}" >> $GITHUB_ENV
          else
            echo "METATAGS=type=sha" >> $GITHUB_ENV
          fi

      - name: Metadata for heighliner
        id: meta-heighliner
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR }}/heighliner
          tags: |
            type=sha

      - name: Prepare heighliner build
        run: |
          curl -vL https://raw.githubusercontent.com/strangelove-ventures/heighliner/main/dockerfile/imported/Dockerfile -o ${{ runner.temp }}/Dockerfile.heighliner
          echo "IMAGE_VERSION=$(echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '.labels["org.opencontainers.image.version"]')" >> $GITHUB_ENV

      - name: Build and push heighliner image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ runner.temp }}/Dockerfile.heighliner
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta-heighliner.outputs.tags }}
          labels: ${{ steps.meta-heighliner.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.GHCR }}/xion
            VERSION=${{ env.IMAGE_VERSION }}
            BINARIES=/usr/bin/xiond
