name: Interchain tests

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build and Push Docker Images]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  go-build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  interchain-tests:
    environment: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_type:
        - "DungeonTransferBlock"
        - "XionSendPlatformFee"
        - "MintModuleNoInflationNoFees"
        - "MintModuleInflationHighFees"
        - "MintModuleInflationLowFees"
        - "JWTAbstractAccount"
        - "XionSendPlatformFee"
        - "XionAbstractAccount"
        - "WebAuthNAbstractAccount"
        - "XionMinimumFeeDefault"
        - "XionMinimumFeeZero"
        - "XionTokenFactory"
        - "XionAbstractAccountJWTCLI"
        - "TreasuryContract"
        - "SingleAbstractAccountMigration"

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21

      - name: checkout
        uses: actions/checkout@v4

      - name: docker xion metadata
        id: meta-xion
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build go test binary
        run: cd integration_tests && go test -c

      - name: Run all up ci test
        run: ./integration_tests/integration_tests.test -test.failfast -test.v -test.run Test${{ matrix.test_type }}
        env:
          E2E_SKIP_CLEANUP: true
          XION_IMAGE: ${{ steps.meta-xion.outputs.tags }}
